### ISSUE TITLE
Suggestion for team leader

### ISSUE THREAD

**Issue by shaunroot** [giero/LGoH-deck-suggester#2]
This may or may not be an issue. Does the app calculate which character should be the leader? If so, is it the first or third character in the list? 

Thanks

**Comment by giero** [comment]
Hey,

Of course it does - leader is marked by red colour and you even have information about what leader skill is used (under the `i` icon).

**Comment by shaunroot** [comment]
I see now! It kept making my 3* hero the leader. I thought it might be marked in red because it was low level. It all makes sense now. Thanks for the awesome app.

I can't wait until the updated spreadsheet gets pushed.

Also, have you considered adding a list to the right that contains all the best characters to bring with your team? I have found that making Freya my leader and bringing along another Freya for 9x damage beats any other combination that I can come up with, even against earth characters. 

Thank again for the awesome tool.

**Comment by giero** [comment]
I have updated it yesterday :) I'm currently working on a tool by which anyone could update heroes database - will be released at the end of this week I think.

Yeah, current event's heroes are overwhelming all decks because of high multipliers - I think I could add such option to disable it during calculations - thanks for this idea, I will add it asap :+1:

**Comment by Marauder69** [comment]
Sorry are you meaning to email me?

I posted a question months ago, nothing recently

**Comment by giero** [comment]
@Marauder69 You've probably got notification from GitHub (not from me directly ;)), because you have set "Watching" in Notifications section for my project.
