### ISSUE TITLE
GvG

### ISSUE THREAD

**Issue by fdussert** [giero/LGoH-deck-suggester#8]
Hello,
great tool, thank you !!!

Do you plan to also generate decks for gvg purpose ?
For example with the last red deck, for gvg, you have to put gladia as leader instead of domi or bestarius.

And also I can help you and contribute if you want, I'm a node dev too ;)

Again, thanks and great work !

**Comment by giero** [comment]
Hey :)

You have to remember that decks generated by this tool depends only on basic stats. GvG has a little bit more complex strategy - it's more based on certain skills to survive. I could add option to generate GvG decks where leaders have purely GvG skills, but that decks will still depend on atk/rec/hp (atk mostly).

Thank you for proposition. For now I paused project developing because of lack of data source from game devs. Spreadsheet is annoying to fill every week, there is no possibility to gather all required data to add more functionalities (like relics).

Also math behind the game itself is to much unknown, to have more realiable results. But with external (and up to date) data source I will start to work on new version. This one is the first one, where I could learn some VueJS basics. The next version should be more organized and better designed. Then I will be glad to get some help :)

**Comment by fdussert** [comment]
Ok understand ;)
Don't hesitate to contact me if you'll start a new version.
best regards
